// Tem que baixar a extenção Rest Client no VS Code
### root
GET http://localhost:3000/

### GET recupera todos os usuarios
GET http://localhost:3000/usuarios/

### Criar Usuario
POST http://localhost:3000/usuarios/
Content-type: application/json

{
    "nome": "Thiago",
    "email": "thiago@gmail.com",
    "senha": "123"
}
// extenção: rest client

###
POST http://localhost:3000/autenticacao/login
Content-type: application/json

{
    "email": "thiago@gmail.com",
    "senha": "123"
}

###
POST http://localhost:3000/autenticacao/login
Content-type: application/json

{
    "email": "leonardo",
    "senha": "321"
}


