// Tem que baixar a extenção Rest Client no VS Code
### root
GET http://localhost:3000/

### GET recupera todos os usuarios
GET http://localhost:3000/usuarios/listar/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoxLCJpYXQiOjE3MjU5MjIxMTcsImV4cCI6MTcyNTkyMjQxN30.fxWqQAAVGuB6Oh8OLEVKNdl8sn1qFSDUnALmjUkBX_I

### Criar Usuario
POST http://localhost:3000/usuarios/criar/
Content-type: application/json

{
    "nome": "Goku",
    "email": "songoku@gmail.com",
    "senha": "123",
    "usuario": "Son"
}
// extenção: rest client

### Login dando certo
POST http://localhost:3000/autenticacao/login
Content-type: application/json

{
    "email": "thiago@gmail.com",
    "senha": "123"
}

### Login dabndo errado
POST http://localhost:3000/autenticacao/login
Content-type: application/json

{
    "email": "leonardo",
    "senha": "321"
}

### acessando perfil
GET  http://localhost:3000/usuarios/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoxLCJpYXQiOjE3MjYwMDQzNzMsImV4cCI6MTcyNjAwNDY3M30.wLN5S3m4rHL0cfXpPf7CASac3DA4aY75Dx7bnVh1rNU
### GET recupera o usuario de id 1
GET http://localhost:3000/usuarios/outroperfil/1

### DELETE apaga o usuario de id 1
DELETE http://localhost:3000/usuarios/apagar/2

### PATCH atualiza o usuario de id 1
PATCH http://localhost:3000/usuarios/atualizar/2
content-type: application/json

{
   "nome": "Clark Kent",
   "email": "clarkent@gmail.com",
   "senha": "123"
}

